language: python

python:
  - "3.6" 

addons:
  postgresql: "9.4"

env:
  - DJANGO=2.1.1 DB=postgres

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install psycopg2-binary

before_script:
   - psql -c "CREATE DATABASE travisci;" -U postgres
   
# command to run tests
script:
  - python manage.py test