# Generated by Django 2.1.1 on 2018-11-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_facility_f_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserved_time_slot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='reserved_time_slot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='reserved_time_slot',
            name='Slot',
            field=models.DateTimeField(null=True),
        ),
    ]
