# Generated by Django 2.1.1 on 2018-11-13 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181111_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserved_time_slot',
            name='Slot',
        ),
        migrations.RemoveField(
            model_name='time_slot',
            name='Slot',
        ),
        migrations.AddField(
            model_name='reserved_time_slot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserved_time_slot',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time_slot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time_slot',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
