# Generated by Django 2.1.1 on 2018-11-19 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181112_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slot',
            name='signup_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
