# Generated by Django 2.1.1 on 2018-12-03 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181118_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slot',
            name='signup_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
